{
 "title": "Youtube parser",
 "description": "Youtube parser metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "youtube_video_unique_emails_found_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(youtube_video_unique_emails_found_total)"
    }
   ]
  },
  {
   "title": "youtube_video_emails_found_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(youtube_video_emails_found_total)"
    }
   ]
  },
  {
   "title": "youtube_video_video_precessed_total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(youtube_video_video_precessed_total)"
    }
   ]
  }
 ]
}